server:
  port: 8084
  
  
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
      - id: EMPLOYEE-SERVICE
        uri: lb://EMPLOYEE-SERVICE
        predicates:
          - Path=/employee/**
          
      - id: DEPARTMENT-SERVICE
        uri: lb://DEPARTMENT-SERVICE
        predicates:
          - Path=/dept/**  
          
      - id: ORGANIZATION-SERVICE
        uri: lb://ORGANIZATION-SERVICE
        predicates:
          - Path=/org/**      
          
    
      
      
      
      
        
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka 
      

